# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_atmosfera_estandar.ui'
#
# Created: Tue Mar 24 04:47:38 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 156)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 114, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_mu = QtGui.QLabel(self.layoutWidget)
        self.label_mu.setObjectName("label_mu")
        self.verticalLayout_5.addWidget(self.label_mu)
        self.label_Vson = QtGui.QLabel(self.layoutWidget)
        self.label_Vson.setObjectName("label_Vson")
        self.verticalLayout_5.addWidget(self.label_Vson)
        self.titulo = QtGui.QLabel(Dialog)
        self.titulo.setGeometry(QtCore.QRect(20, 10, 171, 16))
        self.titulo.setObjectName("titulo")
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(324, 30, 91, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_p = QtGui.QLineEdit(self.widget)
        self.lineEdit_p.setMaxLength(32778)
        self.lineEdit_p.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.verticalLayout.addWidget(self.lineEdit_p)
        self.lineEdit_t = QtGui.QLineEdit(self.widget)
        self.lineEdit_t.setInputMask("")
        self.lineEdit_t.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.verticalLayout.addWidget(self.lineEdit_t)
        self.lineEdit_rho = QtGui.QLineEdit(self.widget)
        self.lineEdit_rho.setInputMask("")
        self.lineEdit_rho.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rho.setObjectName("lineEdit_rho")
        self.verticalLayout.addWidget(self.lineEdit_rho)
        self.widget1 = QtGui.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(114, 30, 91, 48))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_h = QtGui.QLineEdit(self.widget1)
        self.lineEdit_h.setInputMask("")
        self.lineEdit_h.setMaxLength(32767)
        self.lineEdit_h.setCursorPosition(3)
        self.lineEdit_h.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.verticalLayout_2.addWidget(self.lineEdit_h)
        self.lineEdit_deltaT = QtGui.QLineEdit(self.widget1)
        self.lineEdit_deltaT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_deltaT.setObjectName("lineEdit_deltaT")
        self.verticalLayout_2.addWidget(self.lineEdit_deltaT)
        self.widget2 = QtGui.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(50, 30, 56, 51))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_altura = QtGui.QLabel(self.widget2)
        self.label_altura.setObjectName("label_altura")
        self.verticalLayout_3.addWidget(self.label_altura)
        self.label_deltaT = QtGui.QLabel(self.widget2)
        self.label_deltaT.setObjectName("label_deltaT")
        self.verticalLayout_3.addWidget(self.label_deltaT)
        self.widget3 = QtGui.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(240, 30, 84, 91))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_p = QtGui.QLabel(self.widget3)
        self.label_p.setObjectName("label_p")
        self.verticalLayout_4.addWidget(self.label_p)
        self.label_k = QtGui.QLabel(self.widget3)
        self.label_k.setObjectName("label_k")
        self.verticalLayout_4.addWidget(self.label_k)
        self.label_rho = QtGui.QLabel(self.widget3)
        self.label_rho.setObjectName("label_rho")
        self.verticalLayout_4.addWidget(self.label_rho)
        self.widget4 = QtGui.QWidget(Dialog)
        self.widget4.setGeometry(QtCore.QRect(140, 100, 81, 48))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_mu = QtGui.QLineEdit(self.widget4)
        self.lineEdit_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mu.setObjectName("lineEdit_mu")
        self.verticalLayout_6.addWidget(self.lineEdit_mu)
        self.lineEdit_Vson = QtGui.QLineEdit(self.widget4)
        self.lineEdit_Vson.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Vson.setReadOnly(True)
        self.lineEdit_Vson.setObjectName("lineEdit_Vson")
        self.verticalLayout_6.addWidget(self.lineEdit_Vson)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mu.setText(QtGui.QApplication.translate("Dialog", "Viscosidad dinámica [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Vson.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Velocidad Sonido [m/s]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.titulo.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Atmósfera Estandar (ISA)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_p.setText(QtGui.QApplication.translate("Dialog", "101325.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_p.setPlaceholderText(QtGui.QApplication.translate("Dialog", "101325.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_t.setText(QtGui.QApplication.translate("Dialog", "288.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_t.setPlaceholderText(QtGui.QApplication.translate("Dialog", "288.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_rho.setText(QtGui.QApplication.translate("Dialog", "1.2258", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_rho.setPlaceholderText(QtGui.QApplication.translate("Dialog", "1.2258", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_h.setText(QtGui.QApplication.translate("Dialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_h.setPlaceholderText(QtGui.QApplication.translate("Dialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_deltaT.setText(QtGui.QApplication.translate("Dialog", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_deltaT.setPlaceholderText(QtGui.QApplication.translate("Dialog", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_altura.setText(QtGui.QApplication.translate("Dialog", "Altura [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deltaT.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> T ISA [°C]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_p.setText(QtGui.QApplication.translate("Dialog", "Presión [Pa]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_k.setText(QtGui.QApplication.translate("Dialog", "Temperatura [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rho.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Densidad [kg/m<span style=\" vertical-align:super;\">3</span>]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_mu.setText(QtGui.QApplication.translate("Dialog", "1.788e-5", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_mu.setPlaceholderText(QtGui.QApplication.translate("Dialog", "1.788e-5", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Vson.setText(QtGui.QApplication.translate("Dialog", "340.17", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Vson.setPlaceholderText(QtGui.QApplication.translate("Dialog", "340.17", None, QtGui.QApplication.UnicodeUTF8))

