# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_lecturaPerfil.ui'
#
# Created: Sun Mar 29 17:11:43 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(827, 571)
        self.openButton = QtGui.QPushButton(Dialog)
        self.openButton.setGeometry(QtCore.QRect(30, 20, 121, 23))
        self.openButton.setObjectName("openButton")
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(725, 540, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(645, 540, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 50, 441, 391))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelPerfil = QtGui.QLabel(self.frame)
        self.labelPerfil.setGeometry(QtCore.QRect(6, 10, 351, 16))
        self.labelPerfil.setObjectName("labelPerfil")
        self.tableDatos = QtGui.QTableWidget(self.frame)
        self.tableDatos.setGeometry(QtCore.QRect(0, 34, 431, 351))
        self.tableDatos.setObjectName("tableDatos")
        self.tableDatos.setColumnCount(4)
        self.tableDatos.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(3, item)
        self.checkBox_Re3 = QtGui.QCheckBox(Dialog)
        self.checkBox_Re3.setGeometry(QtCore.QRect(30, 480, 70, 17))
        self.checkBox_Re3.setObjectName("checkBox_Re3")
        self.checkBox_Re6 = QtGui.QCheckBox(Dialog)
        self.checkBox_Re6.setGeometry(QtCore.QRect(130, 480, 70, 17))
        self.checkBox_Re6.setObjectName("checkBox_Re6")
        self.checkBox_Re9 = QtGui.QCheckBox(Dialog)
        self.checkBox_Re9.setGeometry(QtCore.QRect(230, 480, 70, 17))
        self.checkBox_Re9.setObjectName("checkBox_Re9")
        self.checkBox_SR = QtGui.QCheckBox(Dialog)
        self.checkBox_SR.setGeometry(QtCore.QRect(330, 480, 121, 17))
        self.checkBox_SR.setObjectName("checkBox_SR")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(605, 0, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(605, 270, 46, 13))
        self.label_3.setObjectName("label_3")
        self.frame_ClAlpha = QtGui.QFrame(Dialog)
        self.frame_ClAlpha.setGeometry(QtCore.QRect(475, 20, 341, 241))
        self.frame_ClAlpha.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_ClAlpha.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ClAlpha.setObjectName("frame_ClAlpha")
        self.frame_CdCl = QtGui.QFrame(Dialog)
        self.frame_CdCl.setGeometry(QtCore.QRect(475, 288, 341, 241))
        self.frame_CdCl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_CdCl.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_CdCl.setObjectName("frame_CdCl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Lectura Perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("Dialog", "Seleccionar Perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Dialog", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPerfil.setText(QtGui.QApplication.translate("Dialog", "Datos del Perfil : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re3.setText(QtGui.QApplication.translate("Dialog", "Re 3 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re6.setText(QtGui.QApplication.translate("Dialog", "Re 6 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re9.setText(QtGui.QApplication.translate("Dialog", "Re 9 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_SR.setText(QtGui.QApplication.translate("Dialog", "Rugocidad Estandar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Cl vs alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Cd vs Cl", None, QtGui.QApplication.UnicodeUTF8))

