# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_lecturaPerfil.ui'
#
# Created: Fri Jan 27 22:16:32 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1032, 737)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(1032, 737))
        Dialog.setSizeIncrement(QtCore.QSize(0, 0))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 1011, 718))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.openButton = QtGui.QPushButton(self.layoutWidget1)
        self.openButton.setMaximumSize(QtCore.QSize(550, 642))
        self.openButton.setObjectName("openButton")
        self.verticalLayout_3.addWidget(self.openButton)
        self.frame = QtGui.QFrame(self.layoutWidget1)
        self.frame.setMinimumSize(QtCore.QSize(550, 642))
        self.frame.setMaximumSize(QtCore.QSize(550, 642))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelPerfil = QtGui.QLabel(self.frame)
        self.labelPerfil.setObjectName("labelPerfil")
        self.verticalLayout_2.addWidget(self.labelPerfil)
        self.tableDatos = QtGui.QTableWidget(self.frame)
        self.tableDatos.setObjectName("tableDatos")
        self.tableDatos.setColumnCount(4)
        self.tableDatos.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableDatos)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_Re3 = QtGui.QCheckBox(self.frame)
        self.checkBox_Re3.setObjectName("checkBox_Re3")
        self.horizontalLayout.addWidget(self.checkBox_Re3)
        self.checkBox_Re6 = QtGui.QCheckBox(self.frame)
        self.checkBox_Re6.setObjectName("checkBox_Re6")
        self.horizontalLayout.addWidget(self.checkBox_Re6)
        self.checkBox_Re9 = QtGui.QCheckBox(self.frame)
        self.checkBox_Re9.setObjectName("checkBox_Re9")
        self.horizontalLayout.addWidget(self.checkBox_Re9)
        self.checkBox_SR = QtGui.QCheckBox(self.frame)
        self.checkBox_SR.setObjectName("checkBox_SR")
        self.horizontalLayout.addWidget(self.checkBox_SR)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cl_vs_aoa_layout = QtGui.QVBoxLayout()
        self.cl_vs_aoa_layout.setObjectName("cl_vs_aoa_layout")
        self.cl_vs_aoa_label = QtGui.QLabel(self.layoutWidget2)
        self.cl_vs_aoa_label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.cl_vs_aoa_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cl_vs_aoa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_vs_aoa_label.setObjectName("cl_vs_aoa_label")
        self.cl_vs_aoa_layout.addWidget(self.cl_vs_aoa_label)
        self.frame_ClAlpha = QtGui.QFrame(self.layoutWidget2)
        self.frame_ClAlpha.setMinimumSize(QtCore.QSize(400, 200))
        self.frame_ClAlpha.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_ClAlpha.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ClAlpha.setObjectName("frame_ClAlpha")
        self.cl_vs_aoa_layout.addWidget(self.frame_ClAlpha)
        self.verticalLayout.addLayout(self.cl_vs_aoa_layout)
        self.cd_vs_cl_layout = QtGui.QVBoxLayout()
        self.cd_vs_cl_layout.setObjectName("cd_vs_cl_layout")
        self.cd_vs_cl_label = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cd_vs_cl_label.sizePolicy().hasHeightForWidth())
        self.cd_vs_cl_label.setSizePolicy(sizePolicy)
        self.cd_vs_cl_label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.cd_vs_cl_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cd_vs_cl_label.setObjectName("cd_vs_cl_label")
        self.cd_vs_cl_layout.addWidget(self.cd_vs_cl_label)
        self.frame_CdCl = QtGui.QFrame(self.layoutWidget2)
        self.frame_CdCl.setMinimumSize(QtCore.QSize(400, 200))
        self.frame_CdCl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_CdCl.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_CdCl.setObjectName("frame_CdCl")
        self.cd_vs_cl_layout.addWidget(self.frame_CdCl)
        self.verticalLayout.addLayout(self.cd_vs_cl_layout)
        self.cm_vs_aoa_layout = QtGui.QVBoxLayout()
        self.cm_vs_aoa_layout.setObjectName("cm_vs_aoa_layout")
        self.cm_vs_aoa_label = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cm_vs_aoa_label.sizePolicy().hasHeightForWidth())
        self.cm_vs_aoa_label.setSizePolicy(sizePolicy)
        self.cm_vs_aoa_label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.cm_vs_aoa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cm_vs_aoa_label.setObjectName("cm_vs_aoa_label")
        self.cm_vs_aoa_layout.addWidget(self.cm_vs_aoa_label)
        self.frame_CmAlpha = QtGui.QFrame(self.layoutWidget2)
        self.frame_CmAlpha.setMinimumSize(QtCore.QSize(400, 200))
        self.frame_CmAlpha.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_CmAlpha.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_CmAlpha.setObjectName("frame_CmAlpha")
        self.cm_vs_aoa_layout.addWidget(self.frame_CmAlpha)
        self.verticalLayout.addLayout(self.cm_vs_aoa_layout)
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.cancelButton = QtGui.QPushButton(self.layoutWidget)
        self.cancelButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        spacerItem1 = QtGui.QSpacerItem(10, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.okButton = QtGui.QPushButton(self.layoutWidget)
        self.okButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.okButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Lectura Perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("Dialog", "Seleccionar Perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPerfil.setText(QtGui.QApplication.translate("Dialog", "Datos del Perfil : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Cl_max", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "beta_max", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "CL_betamax", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "alpha_betamax", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "dbeta_dalpha", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "b_max", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "CD_min", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "CL_CD_max", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "cuspide", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.verticalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "CM0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Re 3*10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Re 6*10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Re 9*10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableDatos.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Std Rought", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re3.setText(QtGui.QApplication.translate("Dialog", "Re 3 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re6.setText(QtGui.QApplication.translate("Dialog", "Re 6 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Re9.setText(QtGui.QApplication.translate("Dialog", "Re 9 10^6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_SR.setText(QtGui.QApplication.translate("Dialog", "Rugocidad Estandar", None, QtGui.QApplication.UnicodeUTF8))
        self.cl_vs_aoa_label.setText(QtGui.QApplication.translate("Dialog", "Cl vs aoa", None, QtGui.QApplication.UnicodeUTF8))
        self.cd_vs_cl_label.setText(QtGui.QApplication.translate("Dialog", "Cd vs Cl", None, QtGui.QApplication.UnicodeUTF8))
        self.cm_vs_aoa_label.setText(QtGui.QApplication.translate("Dialog", "Cm vs aoa", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Dialog", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))

